ubicaciones = ["España", "Inglaterra", "Francia", "México", "RepDominicana"]
print ("ORIGINAL: " , *ubicaciones, sep=(", "))
print ("ALFABETICAMENTE: " , *sorted(ubicaciones), sep=(", "))
print ("ORIGINALx2: " , *ubicaciones, sep=(", "))
print ("ALFABETICO INVERSO: ", *sorted(ubicaciones, reverse = True), sep=(", "))
print ("ORIGINALx3: " , *ubicaciones, sep=(", "))
ubicaciones.reverse()
print ("REVERSE: ", *ubicaciones, sep=(", "))
ubicaciones.reverse()
print ("ORIGINALx4: " , *ubicaciones, sep=(", "))
ubicaciones.sort()
print ("ALFABETICO SORT: ", *ubicaciones, sep=(", "))
ubicaciones.sort(reverse =True)
print ("ALFABETICO INVERSO SORT: ", *ubicaciones, sep=(", "))